# Generated by Django 3.1.3 on 2021-02-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='sku',
            new_name='skus',
        ),
    ]
