# Generated by Django 3.1.3 on 2020-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
