# Generated by Django 3.0.3 on 2020-09-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_codegeneratormodel_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codegeneratormodel',
            old_name='codes',
            new_name='codes1',
        ),
    ]
