# Generated by Django 3.1.3 on 2021-02-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productModel',
        ),
    ]
