# Generated by Django 3.1.3 on 2020-12-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_loadmodel_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='livePost',
            new_name='livePostModel',
        ),
    ]
