# Generated by Django 3.1.3 on 2020-12-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_auto_20201228_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadmodel',
            name='email',
        ),
    ]
