# Generated by Django 3.1.3 on 2021-02-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_auto_20210208_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='item',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='itemmodel',
            old_name='skus',
            new_name='sku',
        ),
    ]
