# Generated by Django 3.1.3 on 2021-02-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0003_auto_20210208_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='cm',
            field=models.FloatField(default=0),
        ),
    ]
