# Generated by Django 3.1.3 on 2020-12-30 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0003_auto_20201230_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livepostmodel',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='livepostmodel',
            old_name='member_id',
            new_name='incharge',
        ),
        migrations.RenameField(
            model_name='livepostmodel',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='livepostmodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='fx.membermodel'),
        ),
        migrations.AddField(
            model_name='livepostmodel',
            name='in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert', to='fx.membermodel'),
        ),
    ]
