# Generated by Django 3.1.3 on 2021-02-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0003_delete_productmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemModels',
            new_name='ProductModel',
        ),
        migrations.RenameModel(
            old_name='ItemSolds',
            new_name='ProductSold',
        ),
    ]
