# Generated by Django 3.0.3 on 2020-09-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0003_auto_20200924_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codegeneratormodel',
            name='codes1',
        ),
    ]
