# Generated by Django 3.0.3 on 2020-09-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0004_remove_codegeneratormodel_codes1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingmodels',
            name='source_id',
        ),
    ]
