# Generated by Django 3.1.3 on 2021-02-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0004_itemmodel_cm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepostmodel',
            name='date_entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
