# Generated by Django 3.1.3 on 2021-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0005_auto_20210208_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venturemodel',
            name='date_entered',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
