# Generated by Django 3.1.3 on 2021-02-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0005_itemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('cm', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('transaction_id', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.itemmodel')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.membermodel')),
            ],
        ),
    ]
