# Generated by Django 3.1.3 on 2020-12-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0005_auto_20201230_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytransactionmodel',
            name='account_code',
            field=models.PositiveIntegerField(choices=[(0, 'SAVING ACCOUNT'), (1, 'WALLET ACCOUNT'), (2, 'CC ACCOUNT'), (3, 'VENTURE ACCOUNT')], default=1),
        ),
    ]
