# Generated by Django 3.1.3 on 2020-12-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0006_auto_20201230_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytransactionmodel',
            name='account_code',
            field=models.PositiveIntegerField(choices=[(0, 'SAVING ACCOUNT'), (1, 'WALLET ACCOUNT'), (2, 'CC ACCOUNT'), (3, 'VENTURE ACCOUNT'), (4, 'PAYMENT ACCOUNT')], default=1),
        ),
        migrations.AlterField(
            model_name='daytransactionmodel',
            name='category',
            field=models.PositiveIntegerField(choices=[(3, 'REGULAR TRANSACTION'), (0, 'PAYMENT'), (2, 'VENTURE'), (4, 'DEPOSIT'), (5, 'WITHRAWAL'), (6, 'GROCERY'), (7, 'SERVICES'), (1, 'LOAN PAYMENT')], default=1),
        ),
    ]
