# Generated by Django 3.1.3 on 2021-02-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0006_itemsold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemSold',
            new_name='ItemsSold',
        ),
    ]
