# Generated by Django 3.1.3 on 2021-02-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0006_auto_20210208_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=13)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('cm', models.FloatField(default=0)),
                ('reg_price', models.FloatField(default=0)),
                ('transaction_id', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.membermodel')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.itemmodel')),
            ],
        ),
    ]
