# Generated by Django 3.0.3 on 2020-09-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0006_auto_20200924_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingmodel',
            name='role_type',
            field=models.CharField(choices=[('B', 'BUYER'), ('S', 'SELLER')], default='S', max_length=1),
        ),
    ]
