# Generated by Django 3.1.3 on 2021-02-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0007_itemsold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsold',
            old_name='reg_price',
            new_name='price',
        ),
    ]
