# Generated by Django 3.1.3 on 2021-02-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0008_auto_20210215_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
