# Generated by Django 3.0.3 on 2020-09-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0009_auto_20200924_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccmodel',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'REGULAR TRANSACTION'), (1, 'TRANSFER'), (2, 'GROCERY'), (3, 'SAVING_INTEREST'), (4, 'EARNED'), (5, 'LOAN'), (6, 'VENTURE'), (7, 'TRADING')], default=0),
        ),
        migrations.AlterField(
            model_name='tradingmodel',
            name='amount',
            field=models.FloatField(verbose_name='AMOUNT'),
        ),
        migrations.AlterField(
            model_name='tradingmodel',
            name='cc',
            field=models.FloatField(default=0, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='venturemodel',
            name='amount',
            field=models.FloatField(verbose_name='AMOUNT'),
        ),
        migrations.AlterField(
            model_name='venturemodel',
            name='cc',
            field=models.FloatField(default=0, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='venturewalletmodel',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'REGULAR TRANSACTION'), (1, 'TRANSFER'), (2, 'GROCERY'), (5, 'LOAN'), (6, 'VENTURE'), (7, 'TRADING')], default=0),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'REGULAR TRANSACTION'), (1, 'TRANSFER'), (2, 'GROCERY'), (5, 'LOAN'), (6, 'VENTURE'), (7, 'TRADING')], default=0),
        ),
    ]
