# Generated by Django 3.1.3 on 2020-12-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0009_auto_20201230_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livepostmodel',
            name='incharge',
        ),
    ]
