# Generated by Django 3.1.3 on 2021-02-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0010_ps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ps',
        ),
    ]
