# Generated by Django 3.1.3 on 2020-12-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0010_remove_livepostmodel_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepostmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
