# Generated by Django 3.1.3 on 2020-12-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0011_livepostmodel_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs')], default='Mr.', max_length=4)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('member_id', models.CharField(blank=True, default='DA1212-1', max_length=11, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='livepostmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
