# Generated by Django 3.0.3 on 2020-10-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0011_tmp_passwordmodel_qrcode_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_passwordmodel',
            name='qrcode_pwd',
            field=models.CharField(default='', max_length=12),
        ),
    ]
