# Generated by Django 3.1.3 on 2020-12-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0012_auto_20201231_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepostmodel',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
