# Generated by Django 3.0.3 on 2020-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0012_auto_20201031_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venturemodel',
            name='amount',
            field=models.FloatField(verbose_name='PHP'),
        ),
        migrations.AlterField(
            model_name='venturemodel',
            name='cc',
            field=models.FloatField(default=0, verbose_name='Comm. Money'),
        ),
    ]
