# Generated by Django 3.0.3 on 2020-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0013_auto_20201031_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venturemodel',
            name='cc',
            field=models.FloatField(default=0, verbose_name='CO. MONEY'),
        ),
    ]
