# Generated by Django 3.1.3 on 2020-12-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0013_auto_20210101_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepostmodel',
            name='remarks',
            field=models.CharField(default='In Progress', max_length=300),
        ),
    ]
