# Generated by Django 3.1.3 on 2020-11-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0014_membermodel_reserve2'),
        ('fx', '0014_auto_20201117_0725'),
    ]

    operations = [
    ]
