# Generated by Django 3.1.3 on 2021-02-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0014_remove_productsold_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='ProductModels',
        ),
    ]
