# Generated by Django 3.1.3 on 2021-02-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0015_auto_20210215_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='ProductModel',
        ),
    ]
