# Generated by Django 3.1.3 on 2021-01-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0015_auto_20210101_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='member_id',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.membermodel'),
        ),
    ]
