# Generated by Django 3.1.3 on 2021-01-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0016_auto_20210101_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='member',
            new_name='profile',
        ),
    ]
