# Generated by Django 3.1.3 on 2021-02-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0016_auto_20210215_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModels',
        ),
        migrations.AddField(
            model_name='productsold',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.productmodel'),
        ),
    ]
