# Generated by Django 3.1.3 on 2020-11-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0016_remove_membermodel_reserve2'),
    ]

    operations = [
        migrations.AddField(
            model_name='venturemodel',
            name='in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_charge', to='fx.membermodel'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='member_id',
            field=models.CharField(default='DA/12/12', max_length=11, unique=True),
        ),
    ]
