# Generated by Django 3.1.3 on 2020-11-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0017_auto_20201122_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_VentureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('note_id', models.IntegerField(default=0)),
                ('change_deposit_id', models.IntegerField(default=0)),
                ('venture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.venturemodel')),
            ],
        ),
    ]
