# Generated by Django 3.1.3 on 2021-02-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0017_auto_20210215_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
