# Generated by Django 3.1.3 on 2021-01-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0017_auto_20210101_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
    ]
