# Generated by Django 3.1.3 on 2021-01-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0018_profilemodel_source_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='source_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.membermodel'),
        ),
    ]
