# Generated by Django 3.1.3 on 2020-11-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0018_temp_venturemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender', models.FloatField(verbose_name='PHP')),
                ('date_entered', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('venture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.venturemodel')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.walletmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Temp_VentureModel',
        ),
    ]
