# Generated by Django 3.1.3 on 2020-11-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0019_auto_20201126_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change_table',
            old_name='tender',
            new_name='change',
        ),
    ]
