# Generated by Django 3.1.3 on 2021-01-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0019_auto_20210101_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
    ]
