# Generated by Django 3.1.3 on 2021-02-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0020_productmodel_srp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsold',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
