# Generated by Django 3.1.3 on 2020-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0020_auto_20201126_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_table',
            name='destination_acct',
            field=models.CharField(blank=True, default='W', max_length=1),
        ),
    ]
