# Generated by Django 3.1.3 on 2021-01-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0020_auto_20210101_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepostmodel',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'MOBILE TOP UP'), (2, 'COMPUTER REPAIR'), (3, 'MECHANIC'), (4, 'CONSTRUCTION'), (5, 'DELIVERY')], default=1),
        ),
    ]
