# Generated by Django 3.1.3 on 2021-03-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0021_auto_20210224_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('note', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
