# Generated by Django 3.1.3 on 2020-11-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0021_change_table_destination_acct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_table',
            name='wallet',
        ),
        migrations.AddField(
            model_name='change_table',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
    ]
