# Generated by Django 3.1.3 on 2021-01-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0022_mechanicmodel_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionmodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repairmodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
    ]
