# Generated by Django 3.1.3 on 2021-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0022_suppliermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='note',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
