# Generated by Django 3.1.3 on 2020-11-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0022_auto_20201129_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change_table',
            old_name='source_id',
            new_name='desctination_acct_id',
        ),
        migrations.RenameField(
            model_name='change_table',
            old_name='destination_acct',
            new_name='destination_acct_code',
        ),
    ]
