# Generated by Django 3.1.3 on 2021-01-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0023_auto_20210104_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadmodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
    ]
