# Generated by Django 3.1.3 on 2020-11-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0023_auto_20201129_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change_table',
            old_name='desctination_acct_id',
            new_name='destination_acct_id',
        ),
    ]
