# Generated by Django 3.1.3 on 2021-03-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0023_auto_20210306_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.suppliermodel')),
            ],
        ),
    ]
