# Generated by Django 3.1.3 on 2021-03-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0024_pricelistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.productmodel'),
        ),
    ]
