# Generated by Django 3.1.3 on 2020-12-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0025_loansummarymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmpVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_loan', models.FloatField(default=300, verbose_name='Max loan allowrd')),
            ],
        ),
    ]
