# Generated by Django 3.1.3 on 2021-01-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0025_livepostmodel_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='member_id',
            field=models.CharField(default='default', max_length=11, unique=True),
        ),
    ]
