# Generated by Django 3.1.3 on 2021-03-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0026_customernotemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customernotemodel',
            name='source_id',
        ),
        migrations.AlterField(
            model_name='customernotemodel',
            name='date_entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
