# Generated by Django 3.1.3 on 2020-12-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0026_tmpvariables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansummarymodel',
            name='percent',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
