# Generated by Django 3.1.3 on 2021-03-07 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0027_auto_20210306_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotemodel',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.membermodel'),
        ),
    ]
