# Generated by Django 3.1.3 on 2020-12-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0027_auto_20201209_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayTransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveIntegerField(choices=[(2, 'REGULAR TRANSACTION'), (0, 'PAYMENT'), (1, 'VENTURE')], default=1)),
                ('date_entered', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('source_type', models.CharField(blank=True, default='C', max_length=1)),
                ('amount', models.FloatField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venture_customer', to='fx.membermodel')),
                ('in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venture_in_charge', to='fx.membermodel')),
            ],
        ),
    ]
