# Generated by Django 3.1.3 on 2021-01-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0027_livepostmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepostmodel',
            name='code',
            field=models.PositiveIntegerField(choices=[(0, 'WAITING FOR APPROVAL'), (2, 'READY'), (1, 'NOT READY'), (3, 'COMPLETE')], default=0),
        ),
    ]
