# Generated by Django 3.1.3 on 2021-03-08 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0028_customernotemodel_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(default=0)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.membermodel')),
            ],
        ),
    ]
