# Generated by Django 3.1.3 on 2020-12-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0029_auto_20201214_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytransactionmodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daytransactionmodel',
            name='source_type',
            field=models.CharField(choices=[(0, 'CASH'), (1, 'WALLET ACCOUNT'), (2, 'SAVING ACCOUNT')], default=0, max_length=1),
        ),
    ]
