# Generated by Django 3.1.3 on 2021-03-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0029_creditlinemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlinemodel',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='whole_sale',
            field=models.FloatField(default=0),
        ),
    ]
