# Generated by Django 3.1.3 on 2021-03-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0031_auto_20210309_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlinemodel',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('D', 'DEPOSIT'), ('W', 'WITHRAW')], default='D', max_length=1),
        ),
    ]
