# Generated by Django 3.1.3 on 2021-01-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0031_joinmodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livepostmodel',
            name='active',
        ),
    ]
