# Generated by Django 3.1.3 on 2020-12-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0033_auto_20201223_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
