# Generated by Django 3.1.3 on 2021-03-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0033_productmodel_hasbarcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'PERSONAL_HYGIENE'), (1, 'CANNED GOODS'), (2, 'DRY GOODS'), (3, 'PRODUCE'), (4, 'DRINKS'), (5, 'OTHER')], default=5),
        ),
    ]
