# Generated by Django 3.1.3 on 2021-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0033_skillcategorymodel_teammembermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategorymodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
