# Generated by Django 3.1.3 on 2021-01-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0034_skillcategorymodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembermodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.skillcategorymodel'),
        ),
    ]
