# Generated by Django 3.1.3 on 2020-12-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0035_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('phone', models.CharField(max_length=124)),
                ('carrier', models.PositiveIntegerField(choices=[(0, 'SMART'), (1, 'GLOBE'), (2, 'DITO'), (3, 'TALK N TEXT'), (4, 'SUN CELLULAR')], default=0)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
