# Generated by Django 3.1.3 on 2021-01-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0035_teammembermodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepostmodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.membermodel'),
        ),
        migrations.AlterField(
            model_name='livepostmodel',
            name='in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.teammembermodel'),
        ),
    ]
