# Generated by Django 3.1.3 on 2021-03-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0036_auto_20210315_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.CharField(max_length=13),
        ),
    ]
