# Generated by Django 3.1.3 on 2021-01-10 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0036_auto_20210111_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepostmodel',
            name='in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fx.teammembermodel'),
        ),
    ]
