# Generated by Django 3.1.3 on 2021-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0037_auto_20210325_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
