# Generated by Django 3.1.3 on 2020-12-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0038_constructionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('phone', models.CharField(max_length=124)),
                ('origin', models.CharField(blank=True, max_length=300, null=True)),
                ('destination', models.CharField(blank=True, max_length=300, null=True)),
                ('receiver', models.CharField(max_length=124)),
                ('pickup', models.DateField(blank=True, null=True)),
                ('identification', models.PositiveIntegerField(choices=[(0, 'Passport'), (1, 'Driver Licence'), (2, 'SSS/GSIS/UMID'), (3, 'Postal ID'), (4, 'TIN ID')], default=1)),
            ],
        ),
    ]
