# Generated by Django 3.1.3 on 2021-03-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0038_productsold_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsold',
            name='active',
        ),
    ]
