# Generated by Django 3.1.3 on 2021-01-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0039_auto_20210111_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepostmodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cus', to='fx.membermodel'),
        ),
        migrations.AlterField(
            model_name='livepostmodel',
            name='in_charge',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inc', to='fx.teammembermodel'),
        ),
    ]
