# Generated by Django 3.1.3 on 2020-12-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0039_deliverymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='livePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(default='DA1212-0', max_length=11, unique=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'READY'), (1, 'NOT READY'), (2, 'ALMOST DONE')], default=1)),
                ('Remarks', models.CharField(max_length=300)),
                ('Category', models.PositiveIntegerField(choices=[(0, 'MOBILE TOP UP'), (1, 'COMPUTER REPAIR'), (2, 'MECHANIC'), (3, 'CONSTRUCTION'), (4, 'DELIVERY')], default=0)),
            ],
        ),
    ]
