# Generated by Django 3.1.3 on 2021-01-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0041_auto_20210113_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='venturemodel',
            name='customer_source_id',
            field=models.IntegerField(default=0),
        ),
    ]
