# Generated by Django 3.1.3 on 2020-12-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0041_auto_20201226_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
