# Generated by Django 3.1.3 on 2020-12-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0042_auto_20201226_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='member_id',
            field=models.CharField(default='DA1212-1', max_length=11, unique=True),
        ),
    ]
