# Generated by Django 3.1.3 on 2020-12-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0044_repairmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
