# Generated by Django 3.1.3 on 2021-01-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0044_auto_20210122_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinmodel',
            name='code',
            field=models.PositiveIntegerField(choices=[(0, 'WAITING FOR APPROVAL'), (1, 'APPROVED'), (2, 'PENDING'), (3, 'DELETED')], default=0),
        ),
    ]
