# Generated by Django 3.1.3 on 2021-01-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0045_joinmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionmodel',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadmodel',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechanicmodel',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairmodel',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
