# Generated by Django 3.1.3 on 2020-12-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0045_mechanicmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionmodel',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Worker'), (1, 'Materials'), (2, 'Mason'), (3, 'Forman')], default=0),
        ),
    ]
