# Generated by Django 3.1.3 on 2021-01-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0046_auto_20210125_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadmodel',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
