# Generated by Django 3.1.3 on 2020-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0047_constructionmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymodel',
            old_name='destination',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='deliverymodel',
            old_name='origin',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='deliverymodel',
            old_name='receiver',
            new_name='recepient',
        ),
        migrations.RemoveField(
            model_name='constructionmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deliverymodel',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='deliverymodel',
            name='pickup',
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='recepient_address',
            field=models.CharField(default='address', max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='recepient_phone',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
