# Generated by Django 3.1.3 on 2021-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0047_loadmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadmodel',
            name='date_entered',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
