# Generated by Django 3.1.3 on 2021-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0048_loadmodel_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadmodel',
            name='date_entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
