# Generated by Django 3.1.3 on 2020-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0048_auto_20201227_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodel',
            name='address',
            field=models.CharField(default='Adddress', max_length=300),
            preserve_default=False,
        ),
    ]
