# Generated by Django 3.1.3 on 2021-01-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0054_auto_20210126_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymodel',
            name='source_id',
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='date_entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.membermodel'),
        ),
    ]
