# Generated by Django 3.1.3 on 2021-02-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0055_auto_20210126_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='daytransactionmodel',
            name='account_code',
            field=models.PositiveIntegerField(choices=[(1, 'SAVING ACCOUNT'), (2, 'WALLET ACCOUNT'), (3, 'CC ACCOUNT'), (4, 'VENTURE ACCOUNT'), (5, 'PAYMENT ACCOUNT')], default=1),
        ),
        migrations.AlterField(
            model_name='venturemodel',
            name='amount',
            field=models.FloatField(verbose_name='AMOUNT (PHP)'),
        ),
    ]
