# Generated by Django 3.1.3 on 2021-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0056_auto_20210205_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
