# Generated by Django 3.1.3 on 2021-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0058_auto_20210205_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'PERSONAL_HYGIENE'), (1, 'CANNED GOODS'), (2, 'DRY GOODS'), (3, 'PRODUCE'), (4, 'OTHER')], default=4),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='reg_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venturemodel',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
