# Generated by Django 3.1.3 on 2021-02-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0059_auto_20210206_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='sku',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
